version: '3'

services:
  tezos:
    container_name: tezos
    volumes:
    - ./:/conf
    - data:/hab/svc/tezos/data
    image: bodymindarts/tezos
    command: "start bodymindarts/tezos --config-from /conf"
    # environment:
    #   HAB_TEZOS: |

  client:
    image: bodymindarts/tezos
    entrypoint:
    - tezos-client
    - -addr
    - tezos
    command: "--help"
    links:
    - tezos
volumes:
  data: {}
