version: '3'

services:
  node:
    container_name: node
    volumes:
    - ./:/conf
    - data:/hab/svc/tezos/data
    image: bodymindarts/tezos-node
    privileged: true
    command: "start bodymindarts/tezos-node --config-from /conf"
    # environment:
    #   HAB_TEZOS: |

  client:
    image: bodymindarts/tezos-node
    entrypoint:
    - tezos-client
    - -addr
    - tezos
    command: "--help"
    links:
    - node
volumes:
  data: {}
